name: build_and_test_and_publish
on:
  push:
    tags: [ '*' ]

permissions:
  contents: write
jobs:
  build-and-test:
    uses: GTNewHorizons/GTNH-Actions-Workflows/.github/workflows/build-and-test.yml@master
    secrets: inherit
  publish:
    needs: build-and-test
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout mod repo
        uses: actions/checkout@v5
        with:
          fetch-depth: 32
          submodules: recursive
      - name: Determine JDK versions
        id: list-jdk-versions
        shell: bash
        run: |
          (
            echo 'java-versions<<EOF'
            echo 8
            echo 17
            echo 21
            if [[ -f gradle/gradle-daemon-jvm.properties ]]; then
              yq -pprops -oprops '.toolchainVersion' gradle/gradle-daemon-jvm.properties
            fi
            echo EOF
          ) | tee -a "${GITHUB_OUTPUT}"

      - name: Set up JDK versions
        uses: actions/setup-java@v5
        with:
          java-version: ${{ steps.list-jdk-versions.outputs.java-versions }}
          distribution: 'zulu'
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v5
        with:
          build-scan-publish: true
          build-scan-terms-of-use-url: "https://gradle.com/terms-of-service"
          build-scan-terms-of-use-agree: "yes"
          validate-wrappers: true
      - name: build
        shell: bash 
        run: |
          chmod +x gradlew
          ./gradlew --build-cache --info --stacktrace build
      - name: generate changelog
        shell: bash
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          echo "Generating changelog notes..."
            export "CHANGELOG_FILE=$(mktemp --suffix=.md)"
            echo "CHANGELOG_FILE=${CHANGELOG_FILE}" >> $GITHUB_ENV
            gh api --method POST -H "Accept: application/vnd.github+json" \
              "/repos/${GITHUB_REPOSITORY}/releases/generate-notes" \
              -f tag_name="${RELEASE_VERSION}" \
              --jq ".body" > "${CHANGELOG_FILE}"
      - name: publish
        uses: Kir-Antipov/mc-publish@v3.3
        with:
          # modrinth-id: Rf3eVYac
          # modrinth-token: ${{ secrets.MODRINTH_TOKEN }}
          # modrinth-dependencies: |
          #   ghjoiQAl(required)

          name: "Release ${{ github.ref_name }}"
          version: ${{ github.ref_name }}
          files: |
            build/libs/!(*-@(dev|sources|javadoc)).jar
          changelog-file: ${CHANGELOG_FILE}

          github-tag: ${{ github.ref_name }}
          github-generate-changelog: true
          github-draft: false
          github-prerelease: false
          github-commitish: dev
          github-discussion: Announcements
          github-token: ${{ secrets.GITHUB_TOKEN }}

          loaders: forge
          game-versions: 1.7.10
          version-type: release

          curseforge-id: 1461983
          curseforge-token: ${{ secrets.CURSEFORGE_UPLOAD_TOKEN }}
          curseforge-dependencies: |
            826970(required)
