name: build_and_test_and_publish
on:
  push:
    tags: [ '*' ]
jobs:
  build-and-test:
    uses: GTNewHorizons/GTNH-Actions-Workflows/.github/workflows/build-and-test.yml@master
    secrets: inherit
  build_publish:
    needs: build-and-test
    runs-on: ubuntu-latest
    env:
      VERSION: ${{ github.ref_name }}
      RELEASE_VERSION: ${{ github.ref_name }}
      SNAPSHOT: ${{ endsWith(github.ref_name, '-snapshot') || contains(github.event.head_commit.message, '[snapshot]') }}
      PRERELEASE: ${{ endsWith(github.ref_name, '-pre') }}
      MAVEN_PUBLISHING_URL: ${{ vars.MAVEN_PUBLISHING_URL || 'https://nexus.gtnewhorizons.com/repository/releases/' }}
    steps:
      - name: checkout repository
        uses: actions/checkout@v6
      - name: setup jdk 21
        uses: actions/setup-java@v5
        with:
          java-version: 21
          distribution: 'microsoft'
          cache: gradle
      - name: "Upload to CurseForge"
        shell: bash
        run: |
          echo "Generating changelog notes..."
          export "CHANGELOG_FILE=$(mktemp --suffix=.md)"
          echo "CHANGELOG_FILE=${CHANGELOG_FILE}" >> $GITHUB_ENV
          gh api --method POST -H "Accept: application/vnd.github+json" \
            "/repos/${GITHUB_REPOSITORY}/releases/generate-notes" \
            -f tag_name="${RELEASE_VERSION}" \
            --jq ".body" > "${CHANGELOG_FILE}"
          
          chmod +x ./gradlew && ./gradlew --build-cache --info --stacktrace -PmavenPublishUrl='${{ env.MAVEN_PUBLISHING_URL }}' assemble publish -x test
        env:
          CURSEFORGE_TOKEN: ${{ secrets.CURSEFORGE_UPLOAD_TOKEN }}
